# Generated by Django 5.1.7 on 2025-03-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_address_order_ticket_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
