# Generated by Django 5.1.7 on 2025-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_phone_number_order_telegram_id_order_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=20, unique=True)),
                ('blogger_name', models.CharField(max_length=100)),
                ('clicks', models.IntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('payments', models.IntegerField(default=0)),
            ],
        ),
    ]
