# Generated by Django 5.1.7 on 2025-04-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_referral_blogger_name_referral_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='clicks',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='leads',
            new_name='start',
        ),
    ]
